### ISSUE TITLE
Funcionalidad a botones de contacto

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/Prestadores-de-servicio-EGAL#53]
Nombre de la historia: funcionalidad de los botones de contacto 
Responsable: Lizzeth Quiroz 
Descripción: como cliente quiero pedir mas Información sobre los servicios ofrecidos

**Comment by Graciela2000** [comment]
![Enviar_correo](https://user-images.githubusercontent.com/77760362/144886398-e18eaceb-7ea5-4c1f-a069-88c3e3ab2f7c.PNG)

**Comment by Anthony4523** [comment]
Los cambios ya funcionan correctamente
